# Generated by Django 3.0.5 on 2021-01-12 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatureroom',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 3, 52, 32, 16626, tzinfo=utc)),
        ),
    ]
