# Generated by Django 3.0.5 on 2020-09-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_auto_20200902_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='imgprofile/'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
