# Generated by Django 3.0.5 on 2021-01-12 04:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_auto_20210112_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatureroom',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 4, 9, 29, 166599, tzinfo=utc)),
        ),
    ]
