# Generated by Django 3.0.5 on 2020-09-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_auto_20200914_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomserver',
            name='buildingRoom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='roomserver',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
