# Generated by Django 3.0.5 on 2021-01-12 22:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_auto_20210112_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatureroom',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 15, 15, 41, 105597, tzinfo=utc)),
        ),
    ]
