# Generated by Django 3.0.5 on 2020-09-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_auto_20200914_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomserver',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
