# Generated by Django 3.0.5 on 2020-09-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_auto_20200914_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomserver',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
