# Generated by Django 3.0.5 on 2021-01-13 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_auto_20210112_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatureroom',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 11, 53, 33, 714274, tzinfo=utc)),
        ),
    ]
