# Generated by Django 3.0.5 on 2020-09-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_profileuser_roomserver_temperatureroom_temperaturestore'),
        ('adminpage', '0005_auto_20200914_1417'),
        ('adminpage', '0002_auto_20200909_0348'),
        ('adminpage', '0003_auto_20200908_0258'),
    ]

    operations = [
    ]
