#!/bin/sh
python3 /var/www/html/Temperature/Arduino/server/send2DB.py

//script target
[Unit]
Description = My Temperature

[Service]
ExecStart=/etc/init.d/arduino.sh

[Install]
WantedBy=multi-user.target

[Unit]
Description = uvicorn daemon
[Service]
User=root
Group=www-data
WorkingDirectory=/var/www/html/Temperature
ExecStart=/bin/uvicorn temperature.asgi:application --port=8081 --ssl-keyfile=./mycert.key --ssl-certfile=./mycert.pem
[Install]
WantedBy=sockets.target

